
name: 2-Hour SMS Follow-up Cron Job

on:
  schedule:
    # Runs every 2 hours.
    # See https://crontab.guru/ for cron syntax.
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab in GitHub for testing

jobs:
  call_sms_follow_up_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call SMS follow-up webhook
        run: |
          curl --request GET \
          --url ${{ secrets.APP_URL }}/api/cron/sms-follow-up \
          --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}' \
          --fail
